config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :users, only: [:index, :show] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :show, :destroy]
  resources :user_instrument, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  validates :status, inclusion: { in: %w(accepted pending declined),
    message: "%{value} is not a valid status" } 
  validates :job_description, presence: true
  validates :location, presence: true
  validates :job_date, presence: true
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  has_many :user_instruments
  has_many :users, through: :user_instruments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :booked_musicians, through: :bookings, source: :user
  has_many :user_instruments
  has_many :instruments, through: :user_instruments

  mount_uploader :photo, PhotoUploader
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

end

app/models/user_instrument.rb
class UserInstrument < ApplicationRecord
  belongs_to :user
  belongs_to :instrument
  validates_uniqueness_of :user_id, :scope => :instrument_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :bio, :is_musician, :rate, :location, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @user = current_user
    if @user.is_musician
      @bookings = Booking.where(booked_musician_id: @user.id)
    else
      @bookings = Booking.where(user_id: @user.id)
    end
  end

  def show
    @booking = Booking.find(params[:id])
    musician_id = @booking.booked_musician_id
    @musician = User.find(musician_id)
    @user = User.find(params[:id])
  end

  def new
    @musician = User.find(params[:user_id])
    @booker = current_user
    @booking = Booking.new
  end

  def create
    @musician = User.find(params[:user_id])
    @booker = current_user
    @booking = Booking.new(booking_params)
    @booking.user = @booker
    @booking.booked_musician_id = @musician.id
    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_path, notice: "Your booking was successfully cancelled." }
      format.json { head :no_content }
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:job_description, :location, :job_date)
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController

  def new
    @instrument = Instrument.new
  end

  def index
    @instruments = Instrument.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @search = {}
    @instruments = Instrument.all
  end
end

app/controllers/user_instrument_controller.rb
class UserInstrumentController < ApplicationController
  def new
    @available_instruments = Instrument.all - current_user.instruments
    @user_instrument = UserInstrument.new
  end
  
  def create
    @user_instrument = UserInstrument.new
    @user_instrument.user = current_user
    @user_instrument.instrument = Instrument.find(params[:instrument])
    @user_instrument.save
    redirect_to user_path(current_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @location = params[:location]
    if params[:location].present?
      instru = Instrument.find(params[:instrument])
      @users = User.where.not(latitude: nil, longitude: nil).near(params[:location], 10).select { |user| user.instruments.include?(instru) }
    elsif params[:instrument].present?
      instru = Instrument.find(params[:instrument])
      @users = User.where.not(latitude: nil, longitude: nil).select { |user| user.instruments.include?(instru) }
    else
      @users = User.where.not(latitude: nil, longitude: nil)
    end

    @markers = @users.map do |user|
      {
        lng: user.longitude,
        lat: user.latitude
      }
    end

    @search = {}
    @instruments = Instrument.all

  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="bookings-container">
  <h1 style="text-align: center;">All your bookings</h1>
<div class="row">

      <% @bookings.each do |booking| %>
        <div class="col-xs-12 col-sm-4 col-sm-offset-3">
          <div class="bookings-card">
              <div class="booked-musician-avatar">
                <% if booking.user.photo.blank? %>
                  <%= cl_image_tag("lbf9irqu7pjyp0zaow8h",
                    width: 120, height: 120, crop: :fill) %>
                <% else %>
                  <% musician = User.find(booking.booked_musician_id) %>
                  <%= cl_image_tag musician.photo, width: 120, height: 120, crop: :fill, class: "booked-avatar"%>
                <% end %>
              </div>
              <div class="booking-description">
                <h3> Where?: <strong> <%= booking.location %> </strong> |
                    When?: <strong><%= booking.job_date %> </strong></h3>
                <p><br> <em><%= booking.job_description %></em></p>
              </div>
              <div class="booking-details">
                <div class="booking-status">
                  <p>Status:</p>
                  <% if booking.status == "accepted" %>
                    <div class="accepted">
                      <p><%= booking.status.upcase %> <i class="fas fa-thumbs-up"></i></p>
                    </div>
                  <% elsif booking.status == "pending" %>
                    <div class="pending">
                      <p><%= booking.status.upcase %> </p>
                    </div>
                  <% elsif booking.status == "declined" %>
                    <div class="declined">
                      <p><%= booking.status.upcase %> <i class="fas fa-thumbs-down"></i></p>
                    </div>
                  <% end %>
                </div>
                <%= link_to 'See more details', booking, class: "details-button" %>
                </div>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-sm-offset-4">
        <div class="booking-card">
          <div class="deviseform">
            <p>Hey <%= @booker.first_name %>!<br><br> We'll send your booking request to:<br><strong><%= @musician.first_name %> <%= @musician.last_name %></strong></p>
            <p>They'll be back in touch shortly to let you know when they accept your booking.</p>
            <%= simple_form_for(@booking, as: :booking, method: :post, url: user_bookings_path(@musician)) do |f| %>
            <%= f.error_notification %>
            <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

            <div class="form-inputs">
              <%= f.input :job_description %>
            </div>

            <div class="form-inputs">
              <%= f.input :location %>
            </div>

            <div class="form-inputs">
              <%= f.input :job_date, as: :string, required: false, input_html: {class: "datepicker"} %>
            </div>

            <div class="form-actions">
              <%= f.submit "Book Now", class: "button" %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/bookings/show.html.erb
 <div class="banner">
  <div class="container bookings">
    <div class="row">
      <div class="col-xs-12 col-sm-4">
        <div class="booking-info">
         <h1>Booking Info</h1>
         <%if @user.photo.blank? %>
         <%= image_tag "logo.png", class: "logo" %>
         <% else %>
         <center><%= cl_image_tag @user.photo, class: "avatar-bordered-small" %></center>
         <% end %>
         <div></div>
         <p><strong>Musician information</strong><br> <%= @musician.first_name %> <%= @musician.last_name %></p>
         <p><strong>Description</strong><br> <%= @booking.job_description %></p>
         <p><strong>Location</strong><br><%= @booking.location %></p>
         <p><strong>Date</strong><br> <%= @booking.job_date %></p>
         <p><strong>Status</strong><br><p><%= @booking.status.upcase %></p>
         <div class="flexbox">
          <%= link_to @booking, method: :delete, data: { confirm: "Are you sure?" }, class: ""  do %>
          <div class="button-delete flex">
            <i class="far fa-trash-alt button-icon"></i>
            <p id="button-text-delete">Delete</p>
          </div>
          <% end %>
          <%= link_to bookings_path, class: "" do %>
          <div class="button-back flex">
            <i class="fas fa-undo button-icon"></i>
            <p id="button-text-back">Back to Bookings</p>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag %>
    <title>Musessions</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_pack_tag "map" %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <% if user_signed_in? %>
    <%= render 'shared/navbar-logged-in' %>
    <% else %>
    <%= render 'shared/navbar-logged-out' %>
    <% end %>
    <%= render 'shared/flashes' %>
    <div style="min-height: calc(100vh - 130px)">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag "map" %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_tag users_path, class: "form", method: :get do %>
  <p>Instrument</p>
    <%= select_tag "instrument", options_from_collection_for_select(@instruments, "id", "name") %><br>
  <p>Where</p>
    <%= text_field_tag :location, params[:location], class: "input", id: "musician_location" %><br>
    <%= submit_tag ("Search"), class: "button" %>
<% end %>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <div class="card">
      <h1>Musessions</h1>
      <p>Find musicians,<br> find sessions.</p>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <%= link_to "https://github.com/joshbolland/musessions/" do %>
      <i class="fab fa-github"></i>
    <% end %>
  </div>
  <div class="footer-copyright">
    Musessions is made with <i class="fas fa-headphones"></i> by the Jammer team
  </div>
</div>

app/views/shared/_navbar-logged-in.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
    <%= link_to image_tag("logo.png", class: "navbar-wagon-brand"), root_path %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to "Search", root_path, class: "navbar-wagon-item navbar-wagon-link"  %>
    <%= link_to "Bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link"  %>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link"  %>
    <%= link_to user_path(current_user) do %>
      <%= cl_image_tag current_user.photo, class: "profilepic" %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar-logged-out.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
<%= link_to image_tag("logo.png", class: "navbar-wagon-brand"), root_path %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= link_to "Sign In", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link"  %>
    <%= link_to "Sign Up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link"  %>
  </div>
</div>

app/views/user_instrument/create.html.erb
<h1>UserInstrument#create</h1>
<p>Find me in app/views/user_instrument/create.html.erb</p>

app/views/user_instrument/new.html.erb
<h1>Hey! Tell us what you play!</h1>
<p>Find me in app/views/user_instrument/new.html.erb</p>
<%= form_tag user_instrument_index_path, class: "form", method: :post do %>
  <p>Instrument</p>
    <%= select_tag "instrument", options_from_collection_for_select(@available_instruments, "id", "name") %><br>
    <%= submit_tag ("Done!"), class: "button" %>
<% end %>

app/views/users/index.html.erb
<div class="search-bar">
  <%= form_tag users_path, method: :get, :class => "form-group row" do %>
    <div class="col-sm-2">
      <%= select_tag "instrument", options_from_collection_for_select(@instruments, "id", "name"), class: "form-control instrument" %>
    </div>
    <div class="col-sm-4">
      <%= text_field_tag :location, params[:location], placeholder: 'Where', class: "input form-control", id: "musician_location" %>
    </div>
    <div class="col-sm-2">
      <%= submit_tag ("Search"), class: "new-search-button form-control" %>
    </div>
  <% end %>
</div>
<div class="content">
  <div class="cards-container">
    <div class="row">
      <div class="col-xs-12 col-md-12">
        <div class="title">
          <% if @users.count == 1 && @location.present? %>
            <h3> <%= @users.count %> musician available in <%= @location %>: </h3>
          <% elsif @users.count == 1 && @location.blank? %>
            <h3> <%= @users.count %> musician available: </h3>
          <% elsif @users.count != 1 && @location.present? %>
            <h3> <%= @users.count %> musicians available in <%= @location %>: </h3>
          <% elsif @users.count != 1 && @location.blank? %>
            <h3> <%= @users.count %> musicians available: </h3>
          <% end %>
        </div>
      </div>
      <% @users.each do |user| %>
        <div class="col-xs-12 col-md-12">
          <div class="result-card">
            <div class="result-avatar-card">
              <% if user.photo.blank? %>
                <%= cl_image_tag("lbf9irqu7pjyp0zaow8h",
                  width: 180, height: 180, crop: :fill) %>
              <% else %>
                <%= cl_image_tag user.photo, class: "avatar-bordered-search" %>
              <% end %>
            </div>
            <div class="result-description-card">
              <h3> <%= user.first_name %> <%= user.last_name %> | <i class="fas fa-map-marker-alt"></i></i> <%= user.location %> </h3>
              <p> | <% user.instruments.each do |instrument| %>
                <%= instrument.name %> |
              <% end %> </p>
              <p> Book from: <em> £<%= user.rate %> </em></p>
            </div>
            <%= link_to 'Check profile', user, class: "result-button" %>
          </div>
        </div>
      <% end %>
      <div class="col-xs-12 col-md-12">
        <div class="new-search">
        </div>
      </div>
    </div>
  </div>
  <div
    id="map"
    data-markers="<%= @markers.to_json %>"
  ></div>
</div>

app/views/users/show.html.erb
<div class="user-banner">
  <div class="container showpage">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <div class="profile_card">
          <div class="paragraph-flex">
            <h1><%= @user.first_name %> <%= @user.last_name %></h1>
            <%if @user.photo.blank? %>
              <%= image_tag "logo.png" %>
            <% else %>
              <%= cl_image_tag @user.photo, class: "avatar-bordered avatar-large" %>
            <% end %>
            <h3>Location: <%= @user.location %></h3>
            <p> | <% @user.instruments.each do |instrument| %>
                    <%= instrument.name %> |
                  <% end %> </p>
            <h3>Day rate: £<%= @user.rate %></h3>
            <% if @user == current_user %>
              <%= button_to "Edit", edit_user_registration_path, method: "get", class: "button-user"%>
            <% elsif user_signed_in? && @user != current_user %>
              <%= button_to "Book", new_user_booking_path(@user), :method => "get", class: "button-user" %>
            <% elsif user_signed_in? == false %>
              <%= button_to "Book", new_user_registration_path, :method => "get", class: "button-user" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="bio_card">
          <h2>Some stuff you might want to know...</h2>
          <p><%= @user.bio %></p>
        </div>
      </div>
    </div>
  </div>
</div>